#!/bin/bash
# Bundle all great-writer modules into a single file
# Usage: ./scripts/bundle.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$ROOT_DIR/great-writer-bundled.md"

cat > "$OUTPUT" << 'HEADER'
# Great Writer — Universal Writing Skill (Bundled Version)

> This is the single-file version of great-writer, for agents that cannot load
> multiple files. For the modular version, see the individual files in core/ and modes/.
> Generated by scripts/bundle.sh — do not edit directly.

HEADER

# Append router (SKILL.md body, skip frontmatter)
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "# Router" >> "$OUTPUT"
echo "" >> "$OUTPUT"
sed -n '/^---$/,/^---$/!p' "$ROOT_DIR/SKILL.md" | tail -n +2 >> "$OUTPUT"

# Append core modules
for f in writing-dna research-protocol humanizer review-protocol; do
  echo "" >> "$OUTPUT"
  echo "---" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  cat "$ROOT_DIR/core/$f.md" >> "$OUTPUT"
done

# Append mode modules
for f in tech-article marketing-copy research-report xiaohongshu technical-docs; do
  echo "" >> "$OUTPUT"
  echo "---" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  cat "$ROOT_DIR/modes/$f.md" >> "$OUTPUT"
done

echo ""
echo "Bundled to: $OUTPUT"
echo "Size: $(wc -c < "$OUTPUT" | tr -d ' ') bytes"
